In [3]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

In [16]:
df=pd.read_csv("mushrooms.csv")
df.shape
print(df)

     type cap_shape cap_surface cap_color bruises odor gill_attachment  \
0       p         x           s         n       t    p               f   
1       e         x           s         y       t    a               f   
2       e         b           s         w       t    l               f   
3       p         x           y         w       t    p               f   
4       e         x           s         g       f    n               f   
5       e         x           y         y       t    a               f   
6       e         b           s         w       t    a               f   
7       e         b           y         w       t    l               f   
8       p         x           y         w       t    p               f   
9       e         b           s         y       t    a               f   
10      e         x           y         y       t    l               f   
11      e         x           y         y       t    a               f   
12      e         b           s       

In [13]:
le=LabelEncoder()
ds=df.apply(le.fit_transform)

In [15]:
data=ds.values
print(data.shape)


(8124, 23)
[[1 5 2 ... 2 3 5]
 [0 5 2 ... 3 2 1]
 [0 0 2 ... 3 2 3]
 ...
 [0 2 2 ... 0 1 2]
 [1 3 3 ... 7 4 2]
 [0 5 2 ... 4 1 2]]


In [21]:
data_y=data[:,0]
data_x=data[:,1:]

In [23]:
x_train,x_test,y_train,y_test=train_test_split(data_x,data_y,test_size=0.2)

In [27]:
print(x_test.shape)

(1625, 22)


In [28]:
np.unique(y_train)

array([0, 1])

In [70]:
def prior_prob(y_train,label):
    total=y_train.shape[0]
    fav=np.sum(y_train==label)
    return fav/float(total)

In [71]:
def cond_prob(x_train,y_train,feature_col,feature_val,label):
    x_filtered=x_train[y_train==label]
    numerator=np.sum(x_filtered[:,feature_col]==feature_val)
    denominator=np.sum(y_train==label)
    
    return(numerator/float(denominator))

In [74]:
def predict(x_train,y_train,x_test):
    classes=np.unique(y_train)
    n_features=x_train.shape[1]
    post_prob=[]
    
    for label in classes:
        likelihood=1.0
        for f in range(n_features):
            cond=cond_prob(x_train,y_train,f,x_test[f],label)
            likelihood*=cond

        prior=prior_prob(y_train,label)
        post_c=prior*likelihood
        post_prob.append(post_c)
    
    pred=np.argmax(post_prob)
    return pred

In [75]:
output = predict(x_train,y_train,x_test[1])
print(output)
print(y_test[1])

1
1
